### PR TITLE
Added script to initialize MySQL database

### PR DESCRIPTION
**Pull request by dlowrey**

### CODE REVIEW

**Review by NilsG-S — APPROVED** [review]
I don't see any problems

**Comment by dlowrey** [comment]
Waiting on `Patient Records` table schema in `Database/README.md` to be completed.

**Comment by dlowrey** [comment]
@NilsG-S @joyellealina @IntJRG  I am finished with the initialization script for our database. I would like to merge it unless any of you are opposed, I have tested it and it works.

**Comment by NilsG-S** [comment]
@dlowrey I have no problems with that

**Pull request merged**
