### PR TITLE
Configure repo

### PR DESCRIPTION
**Pull request by dlowrey**
We need to make sure we all agree on the primary keys and attributes.

### CODE REVIEW

**Review by NilsG-S — APPROVED** [review]
Looks good

**Comment by dlowrey** [comment]
@IntJRG the Databse README.md is missing the `Patient Record` table schema

**Review by joyellealina — APPROVED** [review]
Everything looks good to me!

**Comment by dlowrey** [comment]
Awesome, looks good. Merging now.

**Pull request merged**
